### ISSUE TITLE
Web3.js #5: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Jshanks21** [dappuniversity/web3_examples#5]
I've been working through the web3 tutorial playlist, but have reached a stopping point at video 5. I'm still new to web3 and node and I've been unable to find outside sources to help me solve this issue. 

When I run the code, it returns the txHash with no errors initially. But after a few seconds it gives me the above error message and reports the transaction has been reverted. Below is the full error message: 

`txHash:  0xcb0ea516e2f656c44d170c6a63799b762137ae10e70da8cedae2588aa9eeab9e err:  null

(node:2300) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x95cfca00d0201d8269526f36f1a6627feb92ac21c9c6d4f332d5b8204837d5d4",
  "blockNumber": 5481691,
  "contractAddress": null,
  "cumulativeGasUsed": 526544,
  "from": "0xa8c548c5e0af7051b012566ba2215c0292d26920",
  "gasUsed": 22850,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xfb2e0ffcaa81843c4b7e94f52cc1e203b7b98505",
  "transactionHash": "0xcb0ea516e2f656c44d170c6a63799b762137ae10e70da8cedae2588aa9eeab9e",
  "transactionIndex": 6
}
    at C:\Users\lfege\Github\web3_DeepDive\node_modules\web3-core-method\src\index.js:412:37
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:2300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I know this has something to do with an async function throwing, but I'm struggling to identify it. Any assistance is greatly appreciated.

**Comment by Jshanks21** [comment]
This is the code I have so far:

`const Tx = require('ethereumjs-tx').Transaction
const Web3 = require('web3')
const web3 = new Web3('https://rinkeby.infura.io/....') //Web3 provider or node

const account1 = '0xa8C54...' //Account 1 address
const account2 = '0x02d7...' //Account 2 address

const PK1 = Buffer.from('...', 'hex') //Private key without "0x" prefix
const PK2 = Buffer.from('...', 'hex') //Private key without "0x" prefix

const contractAddress = '0xFb2e0FFcaA81843c4b7e94F52cc1E203B7B98505'
const contractABI = [{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"standard","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"success","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"},{"name":"","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"_initialSupply","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_from","type":"address"},{"indexed":true,"name":"_to","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_owner","type":"address"},{"indexed":true,"name":"_spender","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Approval","type":"event"}]

const contract = new web3.eth.Contract(contractABI, contractAddress)

const data = contract.methods.transfer(account2, 1000).encodeABI()

//Get tx count for nonce
 web3.eth.getTransactionCount(account1, (err, txCount) => {

//Create transaction object
  const txObject = {
    nonce: web3.utils.toHex(txCount),
    gasLimit: web3.utils.toHex(800000),
    gasPrice: web3.utils.toHex(web3.utils.toWei('10', 'gwei')),
    to: contractAddress,
    data: data
  }

//Sign transaction
  const tx = new Tx(txObject, {chain: 'rinkeby', hardfork: 'petersburg'}) //Choose network and hardfork if not default (mainnet, petersburg)
  tx.sign(PK1)

  const serializedTransaction = tx.serialize()
  const raw = '0x' + serializedTransaction.toString('hex')

//Broadcast transaction
  web3.eth.sendSignedTransaction(raw, (err, txHash) => {
    console.log('txHash: ', txHash, 'err: ', err)
  })
})`
